version: "3"

services:
  namenode:
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    build:
      context: namenode

  datanode1:
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    build:
      context: datanode

  datanode2:
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment: 
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    build:
      context: datanode

  datanode3:
    container_name: datanode3
    restart: always
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment: 
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    build:
      context: datanode

  resourcemanager:
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
      - 8031:8031
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop.env
    build:
      context: resourcemanager

  nodemanager1:
    container_name: nodemanager1
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    build:
        context: nodemanager

  nodemanager2:
    container_name: nodemanager2
    restart: always
    environment:  
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    build:
        context: nodemanager

  nodemanager3:
    container_name: nodemanager3
    restart: always
    environment:  
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    build:
        context: nodemanager
  
  historyserver:
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    build:
        context: historyserver
  
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:  
  hadoop_datanode3:  
  hadoop_historyserver:
